{{- $components := fromYaml (include "components" .) }}
{{- $configurations := fromYaml (include "configurations" .) }}
{{- if $components.nodeAgent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nodeAgent.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    {{- include "kspm-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.nodeAgent.name "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/tier: "core"
data:
  config.json: |
    {
        "applicationProfileServiceEnabled": {{ $configurations.runtimeObservability }},
        "relevantCVEServiceEnabled": {{ eq .Values.capabilities.relevancy "enable" }},
        "prometheusExporterEnabled": {{ eq .Values.nodeAgent.config.prometheusExporter "enable" }},
        "runtimeDetectionEnabled": false,
        "httpDetectionEnabled": false,
        "networkServiceEnabled": {{ eq .Values.capabilities.networkPolicyService "enable" }},
        "malwareDetectionEnabled": false,
        "nodeProfileServiceEnabled": {{ eq .Values.capabilities.nodeProfileService "enable" }},
        "seccompServiceEnabled": {{ eq .Values.capabilities.seccompProfileService "enable" }},
        "initialDelay": "{{ .Values.nodeAgent.config.learningPeriod }}",
        "updateDataPeriod": "{{ .Values.nodeAgent.config.updatePeriod }}",
        "nodeProfileInterval": "{{ .Values.nodeAgent.config.nodeProfileInterval }}",
        "maxSniffingTimePerContainer": "{{ .Values.nodeAgent.config.maxLearningPeriod }}",
        {{- if ne .Values.includeNamespaces "" }}
        "includeNamespaces": "{{ .Values.includeNamespaces }}",
        {{- else if ne .Values.excludeNamespaces "" }}
        "excludeNamespaces": "{{ .Values.excludeNamespaces }}",
        {{- end }}
        "exporters": {
          "stdoutExporter": {{- .Values.nodeAgent.config.stdoutExporter }}
        }
    }
{{- end }}
